kind: Deployment
apiVersion: apps/v1
metadata:
  name: @@ARTIFACT_ID@@
  namespace: @@NAMESPACE@@
spec:
  replicas: 2
  selector:
    matchLabels:
      app: @@ARTIFACT_ID@@
  template:
    metadata:
      labels:
        app: @@ARTIFACT_ID@@
    spec:
      restartPolicy: OnFailure
      containers:
      - name: @@ARTIFACT_ID@@
        image: @@IMAGE_TAG@@
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8090
          initialDelaySeconds: 15
          timeoutSeconds: 1
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8090
          initialDelaySeconds: 15
          timeoutSeconds: 1
        ports:
        - containerPort: 8090
---
kind: Service
apiVersion: v1
metadata:
  name: @@ARTIFACT_ID@@
  namespace: @@NAMESPACE@@
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: @@EXTERNAL_PORT@@
    targetPort: 8090
  selector:
    app: @@ARTIFACT_ID@@
