kind: Deployment
apiVersion: apps/v1
metadata:
  name: @@ARTIFACT_ID@@
  namespace: @@NAMESPACE@@
spec:
  replicas: 1
  selector:
    matchLabels:
      app: @@ARTIFACT_ID@@
  template:
    metadata:
      labels:
        app: @@ARTIFACT_ID@@
    spec:
      containers:
      - name: @@ARTIFACT_ID@@
        image: @@IMAGE_TAG@@
        ports:
        - containerPort: 8090
---
kind: Service
apiVersion: v1
metadata:
  name: @@ARTIFACT_ID@@
  namespace: @@NAMESPACE@@
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: @@EXTERNAL_PORT@@
    targetPort: 8090
  selector:
    app: @@ARTIFACT_ID@@
